// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kixomtnyyowbmqookvkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpeG9tdG55eW93Ym1xb29rdmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzM1MDEsImV4cCI6MjA2OTUwOTUwMX0.N-l_wuiEcrtm1nDX2k43kvN5dnYO_M2xCGG1iDilDec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});